### ISSUE TITLE
How to get additional files in resources

### ISSUE THREAD

**Issue by JUJUEZAIWAN** [laituan245/bio_relex#1]
I'm sorry to mention this issue，because I didn't find a way to use umls.Can you tell me how to get additional files in resources? thank you.

**Comment by laituan245** [comment]
Please contact me by email to get the files: tuanml2@illinois.edu

**Comment by happycjksh** [comment]
@JUJUEZAIWAN 老师您好，请问可以把那五个文件发一份给我吗？谢谢。
