### ISSUE TITLE
Files other than datasets are not found in resources, can you give a detailed link?

### ISSUE THREAD

**Issue by chaichai-icon** [laituan245/bio_relex#2]

**Comment by laituan245** [comment]
Please contact me by email to get the files: tuanml2@illinois.edu

**Comment by happycjksh** [comment]
@chaichai-icon 老师您好，请问可以把那五个文件发一份给我吗？谢谢。

**Comment by chaichai-icon** [comment]
Please download the zipped file here:&nbsp;https://drive.google.com/file/d/1iO75aM1-nrCCPdHMIO8nCcV2yhTCq3aQ/view?usp=sharing



这是作者laituan245给的文件地址



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 6, 2023 15:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [laituan245/bio_relex] Files other than datasets are not found inresources, can you give a detailed link? (Issue #2)




 
@chaichai-icon 老师您好，请问可以把那五个文件发一份给我吗？谢谢。

**Comment by happycjksh** [comment]
您好老师，我刚刚尝试了一下，但是这个地址已经失效了。请问可以通过邮件发一份给我吗？

**Comment by happycjksh** [comment]
@chaichai-icon 您好老师，我刚刚尝试了一下，但是这个地址已经失效了。请问可以通过邮件发一份给我吗？

**Comment by happycjksh** [comment]
@chaichai-icon 我的邮箱是dundun235689@163.com
