### ISSUE TITLE
How to get umls file?

### ISSUE THREAD

**Issue by Loratadine96** [laituan245/bio_relex#3]
I found I couldn't find these five files --- umls_embs.pkl

--- umls_rels.txt
--- umls_reltypes.txt
--- umls_semtypes.txt
--- text2graph.pkl

I have download the UMLS-2020aa-fill file and installed in my device. But I don't know how to use it.
Can you tell me how to get additional files in resources? thank you.

I already send email to you email address. Looking forward to your reply.

**Comment by laituan245** [comment]
I closed the issue because I already replied to you by email.

**Comment by happycjksh** [comment]
@NGC2237-wei 老师您好，请问可以把那五个文件发一份给我吗？谢谢。
