### ISSUE TITLE
How to get additional files in resources？

### ISSUE THREAD

**Issue by xiaolinhan** [laituan245/bio_relex#4]
Dear Tuan Lai,

I am a researcher at the university of hong kong. I read your great work entitled 'Joint Biomedical Entity and Relation Extraction with knowledge-Enhanced Collective Inference'. I would like to try your great work by the code you provided at Github. However, I found that additional files in the resources folder can not be found.

Could you please help me with accessing them? Many thanks for your help! I will definitely cite your great work when I have some results.

Best,
Xiaolin Han

**Comment by HeyQXX** [comment]
Hi, thanks for your great work. I'm a researcher of Central South University. I wonder how you get the file "text2graph.pkl" from metamap and how you extract those three files(rels/reltypes/semtypes) from UMLS.

**Comment by laituan245** [comment]
Thanks for your interest. I sent you the files to your email, so I am going to close this issue now.

**Comment by happycjksh** [comment]
@xiaolinhan 老师您好，请问可以把那五个文件发一份给我吗？谢谢。
