### ISSUE TITLE
How to extract the five files in resource folder.

### ISSUE THREAD

**Issue by HeyQXX** [laituan245/bio_relex#5]
Hi! I'm a researcher from Central South University. Thanks for your great work. I'd like to learn from your work. I have UMLS and MetaMap installed on my device, but I don't know how to extract the five files in your resource folder.

--- umls_embs.pkl
--- umls_rels.txt
--- umls_reltypes.txt
--- umls_semtypes.txt
--- text2graph.pkl

Could you please teach me how to obtain these documents? It would be better if you could directly provide these documents to me. If our work comes to fruition, we will certainly cite your work​

**Comment by antonyscerri** [comment]
Hi

I'm also interested in the additional data files. I'm interested in the setup used to generate the text2graph file, which i might be able to infer somewhat if the file is available. There didnt seem to be any code available that generates these files.

Thanks

Tony

**Comment by zztMermory** [comment]
Hello!
Could you explain clearly  how  these files were obtained? Thank you very much!
--- umls_embs.pkl
--- umls_rels.txt
--- umls_reltypes.txt
--- umls_semtypes.txt
--- text2graph.pkl

**Comment by laituan245** [comment]
Hi. Thank you all for your interest. Could you send me an email to tuanml2@illinois.edu (with also some proof that you have access to UMLS)? The reason I am not putting those files online is because of UMLS licensing issue.

**Comment by happycjksh** [comment]
请问可以把文件发一份给我吗？我的邮箱是2277528544@qq.com
