### ISSUE TITLE
Ade dataset

### ISSUE THREAD

**Issue by suexin27** [laituan245/bio_relex#6]
Hi ~ I would like to ask about the "relations" in each data dictionary in ADE dataset,
eg.  "relations":[  
{  
"type": "Adverse-Effect",  
"head": 0,  
"tail": 1  
} 
"orig_id": 83
what does "head: 0" and "tail: 1" mean? and what is "orig_id" ?
Thanks!

**Comment by laituan245** [comment]
Hi.

"head: 0" and "tail: 1" simply means I denote the head and the tail of the relation by 0 and 1 respectively.

For orig_id, if you look at the original ADE dataset, you will see a field with the same name. This field is from there.

http://lavis.cs.hs-rm.de/storage/spert/public/datasets/ade/
