### ISSUE TITLE
How to calculate umls additional files

### ISSUE THREAD

**Issue by Teedos** [laituan245/bio_relex#7]
Hi,
I can't seem to find the scripts you used to calculate the additional UMLS related files and text2graph.pkl.
I also sent you an email on this matter. 
I also hope you could give some insight on how to adapt your work on different datasets (like creating text2graph on different datasets).
Thank you for your work!

**Comment by laituan245** [comment]
I sent the files.
I focused specifically on BioRelEx and ADE in this work. I do not keep the scripts for adapting to different datasets.
